services:
  - type: web
    name: vog-air-quality-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_PREDICTION_API_URL
        value: https://thesis-backend-zrcb.onrender.com
      - key: REACT_APP_API_BASE_URL
        value: https://thesis-backend-zrcb.onrender.com/api
      - key: REACT_APP_FIREBASE_API_KEY
        value: AIzaSyAYrAf_pQjFhwBg5uhEoDdiajahyJubEzw
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        value: air-quality-monitoring-f97b2.firebaseapp.com
      - key: REACT_APP_FIREBASE_DB_URL
        value: https://air-quality-monitoring-f97b2-default-rtdb.asia-southeast1.firebasedatabase.app
      - key: REACT_APP_FIREBASE_PROJECT_ID
        value: air-quality-monitoring-f97b2
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        value: air-quality-monitoring-f97b2.firebasestorage.app
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        value: 390745277112
      - key: REACT_APP_FIREBASE_APP_ID
        value: 1:390745277112:web:2858ecf8e886b83e16ea4d
